import { ArrowRight, BarChart3, Calendar, CheckCircle2, Sparkles } from "lucide-react"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Content",
    description: "Discovers trending topics and generates LinkedIn posts in your unique voice.",
  },
  {
    icon: Calendar,
    title: "Smart Scheduling",
    description: "Set your cadence and time windows. We handle the rest.",
  },
  {
    icon: BarChart3,
    title: "Voice Calibration",
    description: "Teach the AI your tone with examples. Every post sounds like you.",
  },
]

const samplePost = {
  hook: "The best engineers I know don't write more code — they write less.",
  body: "After reviewing 100+ pull requests this quarter, one pattern stands out: the most impactful changes are deletions.\n\n• Removed 200 lines of dead code → 40% faster builds\n• Consolidated 3 duplicate utilities → fewer bugs\n• Deleted a feature nobody used → happier team\n\nComplexity is the silent killer of velocity. The best thing you can ship today might be nothing at all.\n\nWhat's the best code you've deleted recently?",
  author: "Generated by Auto-LinkedIn",
}

export default function Page() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex h-16 items-center justify-between border-b px-6">
        <span className="font-semibold">Auto-LinkedIn</span>
        <div className="flex items-center gap-4">
          <Link href="/sign-in">
            <Button variant="ghost">Sign In</Button>
          </Link>
          <Link href="/sign-in">
            <Button>Get Started</Button>
          </Link>
        </div>
      </header>

      <main className="flex-1">
        <section className="flex flex-col items-center gap-8 px-6 py-24 text-center">
          <Badge variant="secondary" className="text-sm">
            AI-Powered LinkedIn Automation
          </Badge>
          <h1 className="max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
            Build your LinkedIn presence on autopilot
          </h1>
          <p className="max-w-2xl text-lg text-muted-foreground">
            Discover trending content, generate posts in your voice, and publish on schedule. All powered by AI.
            All under your control.
          </p>
          <div className="flex items-center gap-4">
            <Link href="/sign-in">
              <Button size="lg">
                Start Free <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </section>

        <section className="px-6 py-16">
          <div className="mx-auto max-w-5xl">
            <h2 className="mb-8 text-center text-2xl font-semibold">See what a generated post looks like</h2>
            <Card className="mx-auto max-w-xl">
              <CardContent className="p-6">
                <div className="mb-4 flex items-center gap-3">
                  <div className="h-10 w-10 rounded-full bg-primary/10" />
                  <div>
                    <p className="font-medium">Your Name</p>
                    <p className="text-xs text-muted-foreground">{samplePost.author}</p>
                  </div>
                </div>
                <div className="space-y-3 text-sm leading-relaxed">
                  <p className="font-semibold">{samplePost.hook}</p>
                  <p className="whitespace-pre-line text-muted-foreground">{samplePost.body}</p>
                </div>
                <div className="mt-4 flex gap-4 border-t pt-4 text-xs text-muted-foreground">
                  <span>Like</span>
                  <span>Comment</span>
                  <span>Repost</span>
                  <span>Send</span>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>

        <section className="bg-muted/50 px-6 py-16">
          <div className="mx-auto max-w-5xl">
            <h2 className="mb-12 text-center text-2xl font-semibold">How it works</h2>
            <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
              {features.map(feature => (
                <Card key={feature.title}>
                  <CardContent className="flex flex-col items-start gap-3 p-6">
                    <div className="rounded-lg bg-primary/10 p-2">
                      <feature.icon className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="font-medium">{feature.title}</h3>
                    <p className="text-sm text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        <section className="px-6 py-16">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="mb-4 text-2xl font-semibold">What permissions do we need?</h2>
            <div className="space-y-3 text-left">
              {[
                {
                  scope: "r_liteprofile",
                  reason: "Read your basic profile info to identify your LinkedIn account",
                },
                {
                  scope: "r_basicprofile",
                  reason: "Access your profile name and photo for post attribution",
                },
                {
                  scope: "w_member_social",
                  reason: "Create posts on your behalf — this is the core publishing permission",
                },
              ].map(item => (
                <div key={item.scope} className="flex items-start gap-3 rounded-lg border p-4">
                  <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-green-500" />
                  <div>
                    <p className="font-mono text-sm font-medium">{item.scope}</p>
                    <p className="text-sm text-muted-foreground">{item.reason}</p>
                  </div>
                </div>
              ))}
            </div>
            <p className="mt-6 text-sm text-muted-foreground">
              We never access your messages, connections, or any private data.
            </p>
          </div>
        </section>

        <section className="bg-muted/50 px-6 py-24 text-center">
          <div className="mx-auto max-w-xl">
            <h2 className="mb-4 text-2xl font-semibold">Ready to automate your LinkedIn presence?</h2>
            <p className="mb-8 text-muted-foreground">
              Set up in minutes. Your AI content assistant starts working immediately.
            </p>
            <Link href="/sign-in">
              <Button size="lg">
                Get Started Free <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </section>
      </main>

      <footer className="border-t px-6 py-6 text-center text-sm text-muted-foreground">
        Auto-LinkedIn — AI-powered content automation for professionals
      </footer>
    </div>
  )
}
