"use client"

import { useState } from "react"
import { Plus, Sparkles, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

export function StepVoice({
  voiceData,
  onChange,
}: {
  voiceData: { toneDescription: string; examplePosts: string[] }
  onChange: (data: { toneDescription: string; examplePosts: string[] }) => void
}) {
  const [newExample, setNewExample] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [preview, setPreview] = useState("")

  const addExample = () => {
    if (newExample.trim()) {
      onChange({ ...voiceData, examplePosts: [...voiceData.examplePosts, newExample.trim()] })
      setNewExample("")
    }
  }

  const removeExample = (index: number) => {
    onChange({
      ...voiceData,
      examplePosts: voiceData.examplePosts.filter((_, i) => i !== index),
    })
  }

  const generatePreview = async () => {
    if (!voiceData.toneDescription) return
    setIsGenerating(true)
    setPreview(
      "This is a preview of how your AI-generated posts will sound, based on your tone description and example posts. The actual content will be generated by Gemini when your pipeline runs."
    )
    setIsGenerating(false)
  }

  return (
    <div className="space-y-6">
      <div>
        <Label htmlFor="tone" className="text-base">
          Describe your tone
        </Label>
        <p className="mt-1 text-sm text-muted-foreground">
          Write 2–3 sentences about how you want your posts to sound.
        </p>
        <Textarea
          id="tone"
          placeholder="e.g., Professional but approachable. I like to use data-driven insights with a conversational tone. I often start with a contrarian hook and end with a question."
          value={voiceData.toneDescription}
          onChange={e => onChange({ ...voiceData, toneDescription: e.target.value })}
          className="mt-2"
          rows={4}
        />
      </div>

      <div>
        <Label className="text-base">Example posts you liked</Label>
        <p className="mt-1 text-sm text-muted-foreground">
          Paste 1–3 examples of LinkedIn posts that match your style.
        </p>
        <div className="mt-3 space-y-2">
          {voiceData.examplePosts.map((example, index) => (
            <div key={index} className="flex items-start gap-2 rounded-lg border p-3">
              <p className="flex-1 text-sm">{example}</p>
              <button
                type="button"
                onClick={() => removeExample(index)}
                className="shrink-0 text-muted-foreground hover:text-foreground"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>
        {voiceData.examplePosts.length < 3 && (
          <div className="mt-2 flex gap-2">
            <Textarea
              placeholder="Paste an example post here..."
              value={newExample}
              onChange={e => setNewExample(e.target.value)}
              rows={3}
              className="text-sm"
            />
            <Button onClick={addExample} size="icon" className="shrink-0 self-end" disabled={!newExample.trim()}>
              <Plus className="h-4 w-4" />
            </Button>
          </div>
        )}
      </div>

      <div>
        <Button onClick={generatePreview} disabled={!voiceData.toneDescription || isGenerating}>
          <Sparkles className="mr-2 h-4 w-4" />
          {isGenerating ? "Generating..." : "Generate Voice Preview"}
        </Button>
        {preview && (
          <Card className="mt-3">
            <CardContent className="p-4">
              <p className="text-sm font-medium">Voice Preview</p>
              <p className="mt-1 text-sm text-muted-foreground">{preview}</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}
